- hosts: testing
  become: true
  tasks:
    - include_role:
        name: 2PRecuperatorio
    - include_role:
        name: Alta_Usuarios_Zabaleta
    - include_role:
        name: Sudoers_Zabaleta
    - include_role:
        name: Instala-tools_Zabaleta
    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"
