- name: "Rol: Alta_Usuarios_Zabaleta"
  debug:
    msg: "Inicio de tareas dentro del Rol: Alta_Usuarios_Zabaleta"

- name: "Creo grupos GProfesores y GAlumnos"
  become: yes
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items:
   - GProfesores
   - GAlumnos


- name: "Create a user 'Profesor' with a home directory"
  become: yes
  ansible.builtin.user:
    name: Profesor
    create_home: yes
    groups: GProfesores

- name: "Create a user 'Alumno' with a home directory"
  become: yes
  ansible.builtin.user:
    name: Alumno
    create_home: yes
    groups: GAlumnos

- name: "Aviso de exito"
  debug:
    msg: "Archivo Usuarios y Grupos creados"

